// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

#ifndef HELLO_PIMPL_HXX
#define HELLO_PIMPL_HXX

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#ifndef XSDE_OMIT_PAGGR
#  define XSDE_OMIT_PAGGR
#  define HELLO_PIMPL_HXX_CLEAR_OMIT_PAGGR
#endif

#include "hello-pskel.hxx"

#include <xsde/cxx/stack.hxx>

class hello_pimpl: public hello_pskel
{
  public:
  hello_pimpl (bool = false);

  ~hello_pimpl ();

  virtual void
  _reset ();

  virtual void
  pre ();

  // Elements.
  //
  virtual void
  greeting (const ::std::string&);

  virtual void
  name (const ::std::string&);

  virtual ::hello*
  post_hello ();

  public:
  void
  pre_impl (::hello*);

  public:
  struct hello_pimpl_state
  {
    ::hello* hello_;
  };

  hello_pimpl_state hello_pimpl_state_;
  bool hello_pimpl_base_;
};

#ifdef HELLO_PIMPL_HXX_CLEAR_OMIT_PAGGR
#  undef XSDE_OMIT_PAGGR
#endif

#ifndef XSDE_OMIT_PAGGR

// Parser aggregate for the hello element.
//
class hello_paggr
{
  public:
  hello_paggr ();

  void
  pre ()
  {
    this->hello_p_.pre ();
  }

  ::hello*
  post ()
  {
    return this->hello_p_.post_hello ();
  }

  ::hello_pimpl&
  root_parser ()
  {
    return this->hello_p_;
  }

  static const char*
  root_name ();

  static const char*
  root_namespace ();

  void
  reset ()
  {
    this->hello_p_._reset ();
  }

  public:
  ::xml_schema::string_pimpl string_p_;
  ::hello_pimpl hello_p_;
};

#endif // XSDE_OMIT_PAGGR

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

#endif // HELLO_PIMPL_HXX
