// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#include "hello.hxx"

// hello
//

const ::std::string& hello::
greeting () const
{
  return this->greeting_;
}

::std::string& hello::
greeting ()
{
  return this->greeting_;
}

void hello::
greeting (const ::std::string& x)
{
  this->greeting_ = x;
}

const hello::name_sequence& hello::
name () const
{
  return this->name_;
}

hello::name_sequence& hello::
name ()
{
  return this->name_;
}

#include <stdlib.h>
#include <new>

// hello
//

hello::
hello ()
{
}

hello::
~hello ()
{
}

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

