This is a "Hello, world!" example that shows how to use the Embedded
C++/Hybrid mapping to parse XML documents.

The example consists of the following files:

hello.xsd
  XML Schema which describes "hello" instance documents.

hello.xml
  Sample XML instance document.

hello.hxx
hello.cxx

hello-pskel.hxx
hello-pskel.cxx
hello-pimpl.hxx
hello-pimpl.cxx
  Object model (the first pair of files), parser skeletons (the
  second pair) and parser implementations (the third pair). These
  files are generated by the XSD/e compiler from hello.xsd. The
  --generate-parser and --generate-aggregate options were used
  to request the generation of the parsing code.

driver.cxx
  Driver for the example. It first calls the parser that
  constructs the object model from the input XML file. It
  then prints the content of the object model to STDERR.

To run the example on the sample XML instance document simply
execute:

$ ./driver hello.xml

The example reads from STDIN if input file is not specified:

$ ./driver <hello.xml
